# Generated by Django 4.1.7 on 2023-03-09 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_category_tag_blog_category_blog_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="status",
        ),
    ]
