# Generated by Django 4.1.7 on 2023-03-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_remove_blog_subtitle_remove_blog_tags_delete_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to=""
            ),
        ),
    ]
