# Generated by Django 4.1.7 on 2023-03-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_blog_short_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(default=None, to="blog.tag"),
        ),
    ]
